### Check RobotDataset (torch.utils.data.Dataset & imageio): get by index, slow

In [1]:
import torch
from PIL import Image
import itertools
import imageio
import cv2

In [2]:
print (torch.__version__)
print (imageio.__version__)
print (cv2.__version__)

1.4.0
2.9.0
4.1.0


In [3]:
from RobotDataset import RobotDataset

mydataset = RobotDataset(dataset_dir='my_dataset/')

for i in range(30, 35):
    sample = mydataset[i]
    ts = sample['ts']
    obs = sample['touch']
    rgb = sample['rgb']
    depth = sample['depth']
    print (ts, obs.shape, rgb.shape, depth.shape)

1.5 (10,) (360, 640, 3) (360, 640, 3)
1.55 (10,) (360, 640, 3) (360, 640, 3)
1.6 (10,) (360, 640, 3) (360, 640, 3)
1.65 (10,) (360, 640, 3) (360, 640, 3)
1.7 (10,) (360, 640, 3) (360, 640, 3)


### Check RobotIterableDataset (torch.utils.data.IterableDataset & DataLoader & cv2): iterable

In [4]:
from RobotIterableDataset import RobotIterableDataset
from torch.utils.data import DataLoader
import time

mydataset = RobotIterableDataset(dataset_dir='my_dataset/', start=30, end=34)

loader = DataLoader(mydataset)

for i, sample in enumerate(loader):
    ts = sample['ts']
    obs = sample['touch']
    rgb = sample['rgb']
    depth = sample['depth']
    print (ts, obs.shape, rgb.shape, depth.shape)    

tensor([1.5000]) torch.Size([1, 10]) torch.Size([1, 360, 640, 3]) torch.Size([1, 360, 640, 3])
tensor([1.5500]) torch.Size([1, 10]) torch.Size([1, 360, 640, 3]) torch.Size([1, 360, 640, 3])
tensor([1.6000]) torch.Size([1, 10]) torch.Size([1, 360, 640, 3]) torch.Size([1, 360, 640, 3])
tensor([1.6500]) torch.Size([1, 10]) torch.Size([1, 360, 640, 3]) torch.Size([1, 360, 640, 3])
tensor([1.7000]) torch.Size([1, 10]) torch.Size([1, 360, 640, 3]) torch.Size([1, 360, 640, 3])


In [5]:
mydataset_live = RobotIterableDataset(dataset_dir='my_dataset_2/', simulate_live_mode=True)

loader_live = DataLoader(mydataset_live)

start_time = time.time()
for i, sample in enumerate(loader_live):
    ts = sample['ts']
    obs = sample['touch']
    rgb = sample['rgb']
    depth = sample['depth']
    print (ts, obs.shape, rgb.shape, depth.shape)
    print ("--- %s , sec ---" % (time.time()-start_time))

tensor([0.]) torch.Size([1, 10]) torch.Size([1, 360, 640, 3]) torch.Size([1, 360, 640, 3])
--- 0.029706239700317383 , sec ---
tensor([997.]) torch.Size([1, 10]) torch.Size([1, 360, 640, 3]) torch.Size([1, 360, 640, 3])
--- 1.029484510421753 , sec ---
tensor([1342.1000]) torch.Size([1, 10]) torch.Size([1, 360, 640, 3]) torch.Size([1, 360, 640, 3])
--- 1.3775134086608887 , sec ---
tensor([2534.1499]) torch.Size([1, 10]) torch.Size([1, 360, 640, 3]) torch.Size([1, 360, 640, 3])
--- 2.573336124420166 , sec ---
tensor([5947.2002]) torch.Size([1, 10]) torch.Size([1, 360, 640, 3]) torch.Size([1, 360, 640, 3])
--- 5.993436098098755 , sec ---
